package com.cimcitech.cimctd.bean.contact;

import java.util.List;

/**
 * Created by lyw on 2018/4/12.
 */

public class ContactEnumData {
    /*
    *   "data":{
        "NG":[
            {
                "codeId":"NG01",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"管理层",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"管理层",
                "id":115,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"NG02",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"使用部门",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"使用部门",
                "id":116,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"NG03",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"维护部门",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"维护部门",
                "id":117,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"NG04",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"仓管部门",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"仓管部门",
                "id":118,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"NG05",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"财务部门",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"财务部门",
                "id":119,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"NG06",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"采购部门",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"采购部门",
                "id":120,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"NG07",
                "codeName":"内部关系",
                "codeType":"NG",
                "codeValue":"指挥部",
                "createTime":1508169600000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"指挥部",
                "id":121,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            }
        ],
        "RL":[
            {
                "codeId":"RL01",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"很好",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"很好",
                "id":41,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"RL02",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"较好",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"较好",
                "id":42,
                "isState":"1",
                "parentId":null,
                "updateTime":1504454400000,
                "updateUser":null,
                "updater":7844
            },
            {
                "codeId":"RL03",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"一般",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"一般",
                "id":43,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"RL04",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"未接触",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"未接触",
                "id":44,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"RL05",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"未知",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"未知",
                "id":45,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"RL06",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"差",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"差",
                "id":46,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            },
            {
                "codeId":"RL07",
                "codeName":"关系等级",
                "codeType":"RL",
                "codeValue":"很差",
                "createTime":1504454400000,
                "createUser":"系统管理员",
                "creater":13464,
                "ecodeValue":"很差",
                "id":47,
                "isState":"1",
                "parentId":null,
                "updateTime":null,
                "updateUser":null,
                "updater":null
            }
        ]
    },
    */

    private List<EnumBean> NG;
    private List<EnumBean> RL;

    public List<EnumBean> getNG() {
        return NG;
    }

    public void setNG(List<EnumBean> NG) {
        this.NG = NG;
    }

    public List<EnumBean> getRL() {
        return RL;
    }

    public void setRL(List<EnumBean> RL) {
        this.RL = RL;
    }
}
